Rails:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/AbcSize:
  Max: 30

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    inject: reduce

Style/SignalException:
  EnforcedStyle: only_raise

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space
